# Generated by Django 6.0.7 on 2026-09-02 11:23

import apps.common.services.file_uploadings
import functools
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('resume_id', models.CharField(max_length=64, unique=True, verbose_name='resume ID')),
                ('source', models.CharField(choices=[('hh', 'hh.ru'), ('humart', 'humart')], max_length=16, verbose_name='source')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='fingerprint')),
            ],
            options={
                'verbose_name': 'indexed resume',
                'verbose_name_plural': 'indexed resumes',
                'ordering': ('-updated_timestamp',),
            },
        ),
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('file', models.FileField(upload_to=functools.partial(apps.common.services.file_uploadings.FileUploadService.upload_file_handler_path, 'resume_uploads'), verbose_name='file')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('indexed', 'indexed'), ('failed', 'failed')], default='queued', max_length=16, verbose_name='status')),
                ('indexed', models.PositiveIntegerField(default=0, verbose_name='indexed')),
                ('unchanged', models.PositiveIntegerField(default=0, verbose_name='unchanged')),
                ('skipped', models.PositiveIntegerField(default=0, verbose_name='skipped')),
                ('chunks', models.PositiveIntegerField(default=0, verbose_name='chunks')),
                ('sources', models.JSONField(blank=True, default=dict, verbose_name='sources')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='errors')),
            ],
            options={
                'verbose_name': 'resume upload',
                'verbose_name_plural': 'resume uploads',
                'ordering': ('-created_timestamp',),
            },
        ),
    ]
