# Generated by Django 6.0.7 on 2026-09-03 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('vacancy', models.TextField(verbose_name='vacancy')),
                ('general', models.TextField(blank=True, verbose_name='general requirements')),
                ('recruiter', models.TextField(blank=True, verbose_name='recruiter notes')),
                ('filters', models.JSONField(default=dict, verbose_name='filters')),
                ('matrix', models.JSONField(default=dict, verbose_name='score matrix')),
                ('weights', models.JSONField(default=dict, verbose_name='weights')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='total')),
            ],
            options={
                'verbose_name': 'search plan',
                'verbose_name_plural': 'search plans',
                'ordering': ('-created_timestamp',),
            },
        ),
    ]
