services:
  db:
    image: postgres:15.2
    restart: always
    container_name: postgres
    env_file:
      - ./src/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -q -d "$${POSTGRES_DB}" -U "$${POSTGRES_USER}"']
      interval: 5s
      timeout: 5s
      retries: 5
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - 6379
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

  opensearch:
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch
    restart: always
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"

volumes:
  db_data:
    external: true
  opensearch_data:
